user:
    resource: ../src/Module/User/UI/Http/Controller/
    type: annotation
telegram:
    resource: ../src/Module/Telegram/UI/Http/Controller/
    type: annotation
payment:
    resource: ../src/Module/Payment/UI/Http/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

admin:
    resource: ../src/Module/Admin/Controller/
    type:     annotation
