doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/User/Entity'
                prefix: 'App\Module\User\Entity'
                alias: User
            Proxy:
                dir: '%kernel.project_dir%/src/Module/Proxy/Entity'
                is_bundle: false
                prefix: 'App\Module\Proxy\Entity'
                alias: Proxy
            Admin:
                dir: '%kernel.project_dir%/src/Module/Admin/Entity'
                is_bundle: false
                prefix: 'App\Module\Admin\Entity'
                alias: Admin
            Parser:
                dir: '%kernel.project_dir%/src/Module/Parser/Entity'
                is_bundle: false
                prefix: 'App\Module\Parser\Entity'
                alias: Parser
            UrlChecked:
                dir: '%kernel.project_dir%/src/Module/UrlChecked/Entity'
                is_bundle: false
                prefix: 'App\Module\UrlChecked\Entity'
                alias: UrlChecked
            Telegram:
                dir: '%kernel.project_dir%/src/Module/Telegram/Entity'
                is_bundle: false
                prefix: 'App\Module\Telegram\Entity'
                alias: Telegram
            Subscribe:
                dir: '%kernel.project_dir%/src/Module/Subscribe/Entity'
                is_bundle: false
                prefix: 'App\Module\Subscribe\Entity'
                alias: Subscribe

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
