framework:
  messenger:
    failure_transport: failed
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

      parse_url: # Парсинг урлов на объявления
        dsn: '%env(PARSE_URL_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer

      parse_url_checked: # Урлы объявлений на провреку из парсера
        dsn: '%env(CHECK_URL_TRANSPORT_DSN)%'
        serializer: App\Module\Parser\Message\ParseUrlCheckedSerializer

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      App\Module\Parser\Message\ParseUrlMessage: parse_url # Парсинг урлов на объявления
      App\Module\Parser\Message\ParseUrlCheckedMessage: parse_url_checked # Урлы объявлений на провреку из парсера