module.exports = {
    type: 'Тип дома: ',
    floors: 'Этажей в доме: ',
    parking: 'Парковка: ',
    communications: 'Коммуникации: ',
    yard: 'Двор: ',
    countRooms: 'Количество комнат: ',
    totalArea: 'Общая площадь: ',
    infrastructure: 'Инфраструктура: ',
    balconyOrLoggia: 'Балкон или лоджия: ',
    ceilingHeight: 'Высота потолков: ',
    windows: 'Окна: ',
    finishing: 'Отделка: ',
    sellingMethod: 'Способ продажи: ',
    transactionType: 'Вид сделки: ',
    kitchenArea: 'Площадь кухни: ',
    houseArea: 'Площадь дома: ',
    landArea: 'Площадь участка: ',
    landType: 'Категория земель: ',
    wallMaterial: 'Материал стен: ',
    terraceOrVeranda: 'Терраса или веранда: ',
    bathroom: 'Санузел: ',
    transportAccessibility: 'Транспортная доступность: ',
    livingSpace: 'Жилая площадь: ',
    roomType: 'Тип комнат: ',
    technique: 'Техника: ',
    furniture: 'Мебель: ',
    repair: 'Ремонт: ',
    internetAndWifi: 'Интернет и ТВ: ',
    year: 'Год постройки: ',
}