module.exports = {
    countRooms: 'Количество комнат: ',
    totalArea: 'Общая площадь: ',
    floor: 'Этаж: ',
    balconyOrLoggia: 'Балкон или лоджия: ',
    ceilingHeight: 'Высота потолков: ',
    bathroom: 'Санузел: ',
    windows: 'Окна: ',
    finishing: 'Отделка: ',
    sellingMethod: 'Способ продажи: ',
    transactionType: 'Вид сделки: ',
    kitchenArea: 'Площадь кухни: ',
    livingSpace: 'Жилая площадь: ',
    roomType: 'Тип комнат: ',
    technique: 'Техника: ',
    furniture: 'Мебель: ',
    repair: 'Ремонт: ',
    internetAndWifi: 'Интернет и ТВ: ',
}